import { ActivityType } from '../ActivityType';

export interface Activity {
    activeDuration?: number,
    activityLevel?: any[],
    activityName?: string,
    name?: string,
    activityId?: ActivityType,
    activityTypeId?: ActivityType,
    activityParentId?: ActivityType,
    activityParentName?: string,
    averageHeartRate: number,
    calories: number,
    caloriesLink: string,
    distance: number,
    distanceUnit: string,
    duration: number,
    elevationGain: number,
    heartRateLink: string,
    heartRateZones: any[],
    lastModified: string,
    logId: number,
    logType: string,
    manualValuesSpecified: Record<string, any>,
    originalDuration: number,
    originalStartTime: string,
    pace: number,
    source: Record<string, any>,
    speed: number,
    startTime: string,
    steps: number,
    tcxLink: string,
}
