export interface Sleep {
    dateOfSleep: string,
    duration: number,
    efficiency: number,
    endTime: string,
    infoCode: number,
    levels: Record<string, any>,
    logId: number,
    minutesAfterWakeup: number,
    minutesAsleep: number,
    minutesAwake: number,
    minutesToFallAsleep: number,
    startTime: string,
    timeInBed: number,
    type: string,
}
